name: Package CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # =============================================
  #           Swift language linter
  # =============================================
  swift-linter:
    name: Swift linter
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: norio-nomura/action-swiftlint@3.2.1
  
  # =============================================
  #           Source files changes
  # =============================================
  sources-changes:
    name: Source files changes
    needs: [swift-linter]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      swift: ${{ steps.filter.outputs.swift }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            swift:
              - Sources
  
  # =============================================
  #           Test files changes
  # =============================================
  tests-changes:
    name: Test files changes
    needs: [swift-linter]
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      swift: ${{ steps.filter.outputs.swift }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            swift:
              - Tests
                
  # =============================================
  #           Run unit tests
  # =============================================
  unit-tests:
    name: Unit tests
    needs: [sources-changes, tests-changes]
    if: ${{ (needs.sources-changes.outputs.swift != 'false') && (needs.test-changes.outputs.swift != 'false') }}
    timeout-minutes: 20
    runs-on: macos-latest
    steps:
      - uses: fwal/setup-swift@v1.14.0
        with:
          swift-version: 5.5
      - uses: maxim-lobanov/setup-xcode@v1
      - uses: actions/checkout@v3
      - run: |
          xcodebuild \
            -workspace .swiftpm/xcode/package.xcworkspace \
            -scheme EverythingAtOnce \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2' \
            test

  # # =============================================
  # #           Deploy to CocoaPods
  # # =============================================
  # cocoa-pods:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - run: gem install cocoapods
  #   - run: |
  #       set -eo pipefail
  #       pod lib lint --allow-warnings
  #       pod trunk push --allow-warnings
  #     env:
  #       COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
